theme: jekyll-theme-cayman
title: Big House in the Heart of Inner East Portland
tagline: Looking for housemate!
baseurl: ""
paginate: 1
locale: "en"
# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
